---
title: "CS 422 HW8"
author: "Pavani Rangineni"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r}
library(readtext)
library(factoextra)
library(data.table)
library(fpc)
library(cluster)
library(stringr)
library(dbscan)
setwd('C:/Users/rangi/OneDrive/Desktop/CS422/HW8')
```

### Part 2.1.A.1

```{r}
# It is not possible to predict the attributes that should be removed. 
```

### Part 2.1.A.2

```{r}
#The data does not need to be standardized. Every observation has the same unit, and there are no obvious outliers. The data is all numerical.
```

### Part 2.1.A.3

```{r}
text = readtext("file19.txt")
strings = c(text[[2]][1])
list = str_split(strings[[1]],"\n")
print(list)
```

```{r}
row_list <- c()
for (i in 22:87) {
  row_list <- append(row_list, list[[1]][i])
}
print(length(row_list))
final_data <- read.table(textConnection(row_list))
names(final_data) <- c("Name","I","i","C","c","P","p","M","m")
final_data
write.csv(final_data, "final_dataset.csv", row.names=FALSE)
```

### Part 2.1.B.1
```{r}
library(caret)

main_df <- read.csv("final_dataset.csv")
preproc1 <- preProcess(main_df[,c(2:9)], method=c("center", "scale"))
stand_numeric_data <- predict(preproc1, main_df[,c(2:9)])
df <- main_df[2:9]
summary(stand_numeric_data)
fviz_nbclust(na.omit(stand_numeric_data), kmeans, method="silhouette")
fviz_nbclust(stand_numeric_data, kmeans, method="wss")
# From above figures the number of clusters required should be 8
```

### Part 2.1.B.2
```{r}
k_output <- kmeans(df, centers=8) 
fviz_cluster(k_output, data=df)
```

### Part 2.1.B.3
```{r}
k_output$size
```

### Part 2.1.B.4

```{r}
round(k_output$totss, digits = 3)
# total SSE = 568.303
```

### Part 2.1.B.5
```{r}
round(k_output$withinss, digits = 3)
```

### Part 2.1.B.6
```{r}
k1 <- which(k_output$cluster == 1)
k2 <- which(k_output$cluster == 2)
k3 <- which(k_output$cluster == 3)
k4 <- which(k_output$cluster == 4)
k5 <- which(k_output$cluster == 5)
k6 <- which(k_output$cluster == 6)
k7 <- which(k_output$cluster == 7)
k8 <- which(k_output$cluster == 8)
mammals_1 <- c()
for (i in k1) {
  mammals_1 <- append(mammals_1, toString(main_df[i,1]))
}
cat("mammals cluster - 1\n")
cat(mammals_1)
mammals_2 <- c()
for (i in k2) {
  mammals_2 <- append(mammals_2, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 2\n")
cat(mammals_2)

mammals_3 <- c()
for (i in k3) {
  mammals_3 <- append(mammals_3, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 3\n")
cat(mammals_3)

mammals_4 <- c()
for (i in k4) {
  mammals_4 <- append(mammals_4, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 4\n")
cat(mammals_4)

mammals_5 <- c()
for (i in k5) {
  mammals_5 <- append(mammals_5, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 5\n")
cat(mammals_5)

mammals_6 <- c()
for (i in k6) {
  mammals_6 <- append(mammals_6, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 6\n")
cat(mammals_6)

mammals_7 <- c()
for (i in k7) {
  mammals_7 <- append(mammals_7, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 7\n")
cat(mammals_7)

mammals_8 <- c()
for (i in k8) {
  mammals_8 <- append(mammals_8, toString(main_df[i,1]))
}
cat("\n\nmammals cluster - 8\n")
cat(mammals_8)
```


### Part 2.2.A
```{r}
df <- read.csv('s1.csv')
summary(df)
# In summary we see that the min and max of x and y vary vastly. Hence as the range of data is not uniform we can say the data is not standardized
```
### Part 2.2.B.1
```{r}
plot(df)

```

### Part 2.2.B.2

```{r}
# 1. If we count number of cluster from above plot, there are 15 clusters. 
# 2. Few cluster barely overlap with each other
```

### Part 2.2.C.1
```{r}
fviz_nbclust(df, kmeans, method="wss",k.max = 20)
```
### Part 2.2.C.2
```{r}
fviz_nbclust(df, kmeans, method="silhouette",k.max = 20)
```

### Part 2.2.C.3
```{r}
# From above plots we can the approximate number of clusters could be 19. But in 2.2.A, visually the number of clusters are 15.
```

### Part 2.2.D.1
```{r}
k_output <- kmeans(df, centers=19) 
fviz_cluster(k_output, data=df, main="19 Clusters (unscaled)")
```


### Part 2.2.D.2
```{r}
# Clearly from above plot we can see the clusters generated with kmeans are not ideal from what we expected.
```

### Part 2.2.E.1
```{r}
# Minpts = number of parameters x 2 = 4
# Ans = 4
```

### Part 2.2.E.2
```{r}
dbscan::kNNdistplot(df, k = 4)
abline(h = 15000, lty = 2)
abline(h = 24000, lty = 2)
# from below plt eps seems to be between 15000 to 22000
```

### Part 2.2.E.2
```{r}
temp <- fpc::dbscan(df, eps = 22000, MinPts = 4)
plot(temp, df, main = "DBSCAN: eps = 22000")
temp <- fpc::dbscan(df, eps = 24000, MinPts = 4)
plot(temp, df, main = "DBSCAN: eps = 24000")

#From above plots we can say  with eps = 24000 and minPts = 4, we see better 8 clusters
```